import: a16bitsysop/travis-build-configs:docker-apt.yml

env:
  - IMAGE_NAME=a16bitsysop/travistest APK=bash

before_install:
  - VER=$(docker container run --rm alpine sh -c "apk update > /dev/null; apk info -s "$APK" | head -n1 | sed -r 's+$APK-(.*) install.*+\1+g';")
  - VER="$VER"-alpine"$(docker container run --rm alpine cat /etc/alpine-release)"
  - TAG="-t $IMAGE_NAME:$VER"
  - |
      MY_VER="$(wget -q https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags -O - | sed -e 's+.*\"name\": \"++g' -e 's+\"}]++')"
      echo "Alpine Version $VER"
      echo "Docker Version $MY_VER"

install:
  - git clone --depth 3 https://github.com/a16bitsysop/travis-build-configs.git
  - sh travis-build-configs/docker-pass.sh

before_script:
  - sh travis-build-configs/docker-prep.sh

script:
  - sh travis-build-configs/docker-build.sh
