os: linux
dist: bionic
language: minimal

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled IMAGE_NAME=a16bitsysop/travistest APK=bash

before_script:
  - VER=$(docker container run --rm alpine sh -c "apk update > /dev/null; apk info -s "$APK" | head -n1 | sed -r 's+$APK-(.*) install.*+\1+g';")
  - VER="$VER"-alpine"$(docker container run --rm alpine cat /etc/alpine-release)"
  - TAG="-t $IMAGE_NAME:$VER"
  - |
      MY_VER="$(wget -q https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags -O - | sed -e 's+.*\"name\": \"++g' -e 's+\"}]++')"
      echo "Alpine Version $VER"
      echo "Docker Version $MY_VER"
  - sudo apt-get install pass
  - curl -fsSL "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-pass-v0.6.3-amd64.tar.gz" | tar -xvz
  - chmod +x $(pwd)/docker-credential-pass && mkdir bin && mv docker-credential-pass bin/
  - |
      echo -e "%echo Generating a basic OpenPGP key\n%transient-key\n%no-protection\nKey-Type: default\nSubkey-Type: default\nName-Real: Travis Builder\nName-Comment: Travis Builder user\nName-Email: travis@example.com\nExpire-Date: 1\n%commit\n%echo done" > keygen.txt
      gpg --batch --gen-key keygen.txt
      gpg --check-trustdb
      pass init $(gpg --list-secret-keys | grep -A1 ^sec | tail -n1 | sed 's+^[[:space:]]*++')
      echo -e "{\n  \"ServerURL\": \"https://index.docker.io/v1\", \n  \"Username\": \"$DOCKER_USERNAME\", \n  \"Secret\": \"$DOCKER_PASSWORD\"\n}" | ./bin/docker-credential-pass store
      mkdir .docker
      echo -e '{\n\  "credsStore\":\"pass\"\n}' > .docker/config.jason
  - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker login -u "$DOCKER_USERNAME"
script:
  - docker buildx build --platform linux/amd64,linux/386,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7 $TAG -t "$IMAGE_NAME" --push .
  - docker logout
