env:
  - IMAGE_NAME=a16bitsysop/travistest APK=bash

import: a16bitsysop/travis-build-configs:docker.yml

before_install:
  - VER=$(docker container run --rm alpine sh -c "apk update > /dev/null; apk info -s "$APK" | head -n1 | sed -r 's+$APK-(.*) install.*+\1+g';")
  - VER="$VER"-alpine"$(docker container run --rm alpine cat /etc/alpine-release)"
  - TAG="-t $IMAGE_NAME:$VER"
  - |
      MY_VER="$(wget -q https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags -O - | sed -e 's+.*\"name\": \"++g' -e 's+\"}]++')"
      echo "Alpine Version $VER"
      echo "Docker Version $MY_VER"

install:
  - a16bitsysop/travis-build-configs:docker-pass.sh
#before_scrips:

#script:

