#!/bin/bash

#install multiarch if running on docker hub or travis
if [ -n $DOCKER_REPO ] || [ -n $TRAVIS ]
then
#	docker run --rm --privileged multiarch/qemu-user-static:register --reset
	mkdir -p ~/.docker/cli-plugins
	wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
	chmod a+x ~/.docker/cli-plugins/docker-buildx
	echo '{"experimental":"enabled"}' >> ~/.docker/config.json
	sudo systemctl docker restart
	docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
fi

[ -n $TRAVIS ] && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker buildx build --platform linux/amd64,linux/386,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7 -t "$IMAGE_NAME:1" -t "$IMAGE_NAME" --push .
