#!/bin/sh

#install multiarch if running on docker hub or travis
if [ -n $DOCKER_REPO ] || [ -n $TRAVIS ]
then
	export DOCKER_BUILDKIT=1
	docker build --platform=local -o . git://github.com/docker/buildx
	mkdir -p ~/.docker/cli-plugins
	mv buildx ~/.docker/cli-plugins/docker-buildx

#	chmod a+x ~/.docker/cli-plugins/docker-buildx
#	systemctl docker restart
	docker run --rm --privileged multiarch/qemu-user-static:register --reset
#	docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
fi

#[ -n $TRAVIS ] && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx create --use
docker buildx build --platform linux/amd64,linux/386,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7 -t "$IMAGE_NAME" .
